### ISSUE TITLE
Decompilation Error in decompiling raw code objects

### ISSUE THREAD

**Issue by user-dead** [rocky/python-decompile3#103]
## Description
I was up against a pyarmor binary , extracted all of those pyc files and tried to inject code in memory with [This tool](https://github.com/call-042PE/PyInjector) worked fine , i used the following code to dump the code objects in marshal format:
```py
import inspect, marshal, dis

lmao = globals()
for lol in lmao.keys():
    try:
        xd = inspect.getmembers(lmao[f'{lol}'](),predicate=inspect.ismethod)
        for bruh in xd:
            try:
                marshal.dump(bruh[1].__code__, open(f'..\\test_{bruh[1].__name__}', 'wb'))
            except Exception as e:
                print(e)
                print(bruh[1].__code__)
    except Exception as e:
        print("Module Name:", lol)
        print("Exception", e)
```
after that i run decompyle3 on the files via a script as follows:
```py
import marshal
from decompyle3.main import decompile
import sys
import marshal, os
res = []
for path in os.listdir("..\\"):
    # check if current path is a file
    if os.path.isfile(os.path.join("..\\", path)):
        res.append(path)
for i in res:
    try:
        code = marshal.load(open(f"..\\{i}", 'rb'))
        print(decompile(code, (3,8), sys.stdout))
    except Exception as e:
        print(e)
 ```
 the thing is in most of the cases i get the following error:
 ```
 # decompyle3 version 3.9.0
# Python bytecode version base 3.7
# Decompiled from: Python 3.8.7 (default, Jun 22 2022, 20:39:15) [MSC v.1932 32 bit (Intel)]
# Embedded file name: C:\Users\deadinside\AppData\Local\Programs\Python\Python38-32\lib\tkinter\font.py
return self.cget(key)<decompyle3.semantics.pysource.SourceWalker object at 0x0271CD30>
# decompyle3 version 3.9.0
# Python bytecode version base 3.7
# Decompiled from: Python 3.8.7 (default, Jun 22 2022, 20:39:15) [MSC v.1932 32 bit (Intel)]
# Embedded file name: <frozen main>

-- Stacks of completed symbols:
START ::= |- stmts .
--- This code section failed: ---

 L.2617         0  JUMP_FORWARD         18  'to 18'
                2  NOP
                4  NOP

 L.2618         6  POP_BLOCK
                8  <53>
               10  NOP
               12  NOP
               14  NOP

 L.2619        16  JUMP_FORWARD         64  'to 64'
             18_0  COME_FROM             0  '0'
               18  LOAD_GLOBAL              __armor_enter__
               20  CALL_FUNCTION_0       0  '0 positional arguments'
               22  POP_TOP
               24  NOP
               26  NOP
               28  NOP
               30  SETUP_FINALLY        64  'to 64'
               32  <191>               179  ''
               34  BINARY_SUBSCR
               36  YIELD_VALUE
               38  DELETE_NAME          66  66
               40  BINARY_ADD
               42  <186>                34  ''
               44  BUILD_MAP_UNPACK_WITH_CALL_223   223
               46  <35>
               48  <48>
               50  <41>
               52  <40>
               54  BUILD_TUPLE_UNPACK_171   171
               56  BUILD_MAP_UNPACK_WITH_CALL_180   180
               58  STORE_SUBSCR
               60  RETURN_VALUE
               62  END_FINALLY
             64_0  COME_FROM_FINALLY    30  '30'
             64_1  COME_FROM            16  '16'
               64  LOAD_GLOBAL              __armor_exit__
               66  CALL_FUNCTION_0       0  '0 positional arguments'
               68  POP_TOP
               70  END_FINALLY
               72  RETURN_VALUE
               74  NOP
               76  NOP
               78  NOP
               80  UNARY_NEGATIVE
               82  JUMP_IF_TRUE_OR_POP    43  'to 43'
               84  <35>
               86  <54>
               88  BINARY_TRUE_DIVIDE
               90  <32>
               92  <230>               226  ''
               94  EXTENDED_ARG         65  0x41 << 16 = 16640

Parse error at or near `None' instruction at offset -1
```
and in some cases i get 
```
# decompyle3 version 3.9.0
# Python bytecode version base 3.7
# Decompiled from: Python 3.8.7 (default, Jun 22 2022, 20:39:15) [MSC v.1932 32 bit (Intel)]
# Embedded file name: <frozen imcommunication>
Traceback (most recent call last):
  File ".\decompile.py", line 7, in <module>
    print(decompile(code, (3,7), sys.stdout))
  File "C:\Users\deadinside\AppData\Local\Programs\Python\Python38-32\lib\site-packages\decompyle3\main.py", line 158, in decompile
    deparsed = deparse_fn(
  File "C:\Users\deadinside\AppData\Local\Programs\Python\Python38-32\lib\site-packages\decompyle3\semantics\pysource.py", line 1104, in code_deparse
    tokens, customize = scanner.ingest(
  File "C:\Users\deadinside\AppData\Local\Programs\Python\Python38-32\lib\site-packages\decompyle3\scanners\scanner37.py", line 81, in ingest
    new_tokens = self.bound_collection(
  File "C:\Users\deadinside\AppData\Local\Programs\Python\Python38-32\lib\site-packages\decompyle3\scanners\scanner37base.py", line 195, in bound_collection
    assert count <= i
AssertionError
```
any suggestions on where i went wrong would be really helpful
im attaching the two testcases in this issue
[test___init__.log](https://github.com/rocky/python-decompile3/files/8968415/test___init__.log)
[test_get_IM_hit_url.log](https://github.com/rocky/python-decompile3/files/8968418/test_get_IM_hit_url.log)
other than that , if u wanna look at the pyc files here is the zip 
[weirdflex.zip](https://github.com/rocky/python-decompile3/files/8968441/weirdflex.zip)

Thanks in advance

**Comment by rocky** [comment]
This isn't valid bytecode. All of the places where you see `<dd>` indicate an invalid opcode
