### ISSUE TITLE
Decompiled failed with assetion error at `assert expr[0] == "LOAD_STR"` in customize37.py

### ISSUE THREAD

**Issue by BradMichelle** [rocky/python-decompile3#141]
## Description

Decompiled failed with assetion error at `assert expr[0] == "LOAD_STR"` in customize37.py

## How to Reproduce
Run latest decompyle3 built from source, with the upd.pyc file attached

# file upd.pyc (zipped)
[upd.zip](https://github.com/rocky/python-decompile3/files/11763479/upd.zip)

## Output Given

```

Traceback (most recent call last):
 
  File "C:\Src\python-decompile3\decompyle3\main.py", line 158, in decompile
    deparsed = deparse_fn(
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 1190, in code_deparse
    deparsed.gen_source(
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 980, in gen_source
    self.text = self.traverse(tree, is_lambda=is_lambda)
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 429, in traverse
    self.preorder(node)
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 407, in preorder
    super(SourceWalker, self).preorder(node)
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 407, in preorder
    super(SourceWalker, self).preorder(node)
  File "C:\Src\python-decompile3\decompyle3\semantics\customize37.py", line 998, in n_function_def
    self.default(node)
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 799, in default
    self.template_engine(table[key.kind], node)
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 691, in template_engine
    self.preorder(node[index])
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 407, in preorder
    super(SourceWalker, self).preorder(node)
  File "C:\Src\python-decompile3\decompyle3\semantics\n_actions.py", line 954, in n_mkfunc
    make_function36(self, node, is_lambda=False, code_node=code_node)
  File "C:\Src\python-decompile3\decompyle3\semantics\make_function36.py", line 350, in make_function36
    self.gen_source(
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 980, in gen_source
    self.text = self.traverse(tree, is_lambda=is_lambda)
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 429, in traverse
    self.preorder(node)
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 407, in preorder
    super(SourceWalker, self).preorder(node)
  File "C:\Src\python-decompile3\decompyle3\semantics\n_actions.py", line 83, in n_assign
    self.default(node)
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 799, in default
    self.template_engine(table[key.kind], node)
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 722, in template_engine
    self.preorder(node[index])
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 407, in preorder
    super(SourceWalker, self).preorder(node)
  File "C:\Src\python-decompile3\decompyle3\semantics\n_actions.py", line 659, in n_expr
    self.preorder(node[0])
  File "C:\Src\python-decompile3\decompyle3\semantics\pysource.py", line 407, in preorder
    super(SourceWalker, self).preorder(node)
  File "C:\Src\python-decompile3\decompyle3\semantics\customize37.py", line 1447, in n_joined_str
    assert expr[0] == "LOAD_STR"
AssertionError
```

## Expected behavior

The decompiler can create a compileable source file.

## Environment
decompyle3 built from latest source https://github.com/rocky/python-decompile3/commit/72f91694dab9f69e83dd6f042801c7f8a2922745

Python bytecode version base 3.8.0 (3413)
Decompiled from: Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

**Comment by severin-richner** [comment]
Could reproduce error and it seems like what we actually have there at `expr[0]` isn't just `"LOAD_STR"`, but the following:
```
or (2)
     0. or_parts
        expr_pjit (2)
             0. expr
                call (3)
                     0. expr
                        attribute37 (2)
                             0. expr
                                 L.  36         0  LOAD_GLOBAL              rsession
                             1.                 2  LOAD_METHOD              success
                     1. expr
                                        4  LOAD_FAST                'resp'
                     2.                 6  CALL_METHOD_1         1  ''
             1.                 8  POP_JUMP_IF_TRUE    120  'to 120'
     1. expr
         L.  37        10  LOAD_STR                 'Server returned '
```
It does contain `LOAD_STR` at the end, but maybe this is a parsing error?

**Comment by rocky** [comment]
It is not a parse error but an error in what is acceptable in what is acceptable in the semantic action in `customize.py`.
