### ISSUE TITLE
Exception has occurred: AttributeError 'Instruction' object has no attribute 'tos_str'

### ISSUE THREAD

**Issue by BradMichelle** [rocky/python-decompile3#152]
## Description

Exception has occurred: AttributeError 'Instruction' object has no attribute 'tos_str'

## How to Reproduce

- run any test that go to scanner37base.py at line 669

## Output Given

![image](https://github.com/rocky/python-decompile3/assets/66589426/06a8abfb-8130-4802-9f32-a406cb3245e1)

```
Instruction' object has no attribute 'tos_str'
  File "F:\GitRepo\python-decompile3\decompyle3\scanners\scanner37base.py", line 669, in ingest
    tos_str=inst.tos_str,
  File "F:\GitRepo\python-decompile3\decompyle3\scanners\scanner37.py", line 65, in ingest
    tokens, customize = Scanner37Base.ingest(
  File "F:\GitRepo\python-decompile3\decompyle3\scanners\scanner38.py", line 67, in ingest
    tokens, customize = super(Scanner38, self).ingest(
  File "F:\GitRepo\python-decompile3\decompyle3\semantics\pysource.py", line 1120, in code_deparse
    tokens, customize = scanner.ingest(
  File "F:\GitRepo\python-decompile3\decompyle3\main.py", line 158, in decompile
    deparsed = deparse_fn(
  File "F:\GitRepo\python-decompile3\decompyle3\main.py", line 238, in decompile_file
    decompile(
  File "F:\GitRepo\python-decompile3\decompyle3\main.py", line 337, in main
    deparsed_objects = decompile_file(
  File "F:\GitRepo\python-decompile3\test_a3d\00_run.py", line 4, in <
```

## Expected behavior

No bug

## Workarounds

Nothing

**Comment by rocky** [comment]
This is a new feature of in the master version of `xdis`. (This is one reason that "environment section" is listed and should have been filled out.)  Are you sure you have that updated. Note - CI tests are not failing.

**Comment by OwnerCM** [comment]
> This is a new feature of in the master version of `xdis`. (This is one reason that "environment section" is listed and should have been filled out.) Are you sure you have that updated. Note - CI tests are not failing.

I downloaded the latest master code and the same problem occurred when running it. How to solve it?

# decompyle3 version 3.9.1.dev0
# Python bytecode version base 3.8.0 (3413)
# Decompiled from: Python 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: <frozen cl>
Traceback (most recent call last):
  File "\\?\D:\CZSC\anaconda3\envs\clpy38\Scripts\decompyle3-script.py", line 33, in <module>
    sys.exit(load_entry_point('decompyle3', 'console_scripts', 'decompyle3')())
  File "D:\CZSC\anaconda3\envs\clpy38\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\CZSC\anaconda3\envs\clpy38\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\CZSC\anaconda3\envs\clpy38\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\CZSC\anaconda3\envs\clpy38\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\bin\decompile.py", line 146, in main_bin
    result = main(
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\main.py", line 337, in main
    deparsed_objects = decompile_file(
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\main.py", line 238, in decompile_file
    decompile(
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\main.py", line 158, in decompile
    deparsed = deparse_fn(
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 1120, in code_deparse
    tokens, customize = scanner.ingest(
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\scanners\scanner38.py", line 67, in ingest
    tokens, customize = super(Scanner38, self).ingest(
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\scanners\scanner37.py", line 65, in ingest
    tokens, customize = Scanner37Base.ingest(
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\scanners\scanner37base.py", line 669, in ingest
    tos_str=inst.tos_str,
AttributeError: 'Instruction' object has no attribute 'tos_str'

**Comment by OwnerCM** [comment]
> > This is a new feature of in the master version of `xdis`. (This is one reason that "environment section" is listed and should have been filled out.) Are you sure you have that updated. Note - CI tests are not failing.
> 
> I downloaded the latest master code and the same problem occurred when running it. How to solve it?


This can be solved by updating the xdis module through the xdis source code
