### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by OwnerCM** [rocky/python-decompile3#155]
## Description
TypeError: argument of type 'int' is not iterable

## How to Reproduce
I compiled it using Python 3.7.8, the test.pyc file attached
[test.zip](https://github.com/rocky/python-decompile3/files/12644306/test.zip)

## Output Given
L.2736       318  LOAD_GLOBAL              int
                 320  LOAD_FAST                'cross_num'
                 322  LOAD_CONST               3
                 324  BINARY_TRUE_DIVIDE
                 326  CALL_FUNCTION_1       1  '1 positional argument'
                 328  LOAD_GLOBAL              query_macd_ld
                 330  LOAD_FAST                'self'
                 332  LOAD_FAST                'lines'
                 334  LOAD_CONST               0
                 336  BINARY_SUBSCR
                 338  LOAD_ATTR                start
                 340  LOAD_FAST                'lines'
                 342  LOAD_CONST               -1
                 344  BINARY_SUBSCR
                 346  LOAD_ATTR                end
                 348  CALL_FUNCTION_3       3  '3 positional arguments'
                 350  BUILD_TUPLE_2         2
->               352  RETURN_VALUE
Traceback (most recent call last):
  File "\\?\D:\CZSC\anaconda3\envs\clpy37\Scripts\decompyle3-script.py", line 33, in <module>
    sys.exit(load_entry_point('decompyle3', 'console_scripts', 'decompyle3')())
  File "D:\CZSC\anaconda3\envs\clpy37\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\CZSC\anaconda3\envs\clpy37\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\CZSC\anaconda3\envs\clpy37\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\CZSC\anaconda3\envs\clpy37\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\bin\decompile.py", line 157, in main_bin
    stop_offset=stop_offset,
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\main.py", line 347, in main
    stop_offset,
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\main.py", line 255, in decompile_file
    stop_offset=stop_offset,
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\main.py", line 166, in decompile
    stop_offset=stop_offset,
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 1218, in code_deparse
    debug_opts=debug_opts,
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 983, in gen_source
    self.text = self.traverse(tree, is_lambda=is_lambda)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 430, in traverse
    self.preorder(node)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 408, in preorder
    super(SourceWalker, self).preorder(node)
  File "D:\CZSC\anaconda3\envs\clpy37\lib\site-packages\spark_parser\ast.py", line 117, in preorder
    self.preorder(kid)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 408, in preorder
    super(SourceWalker, self).preorder(node)
  File "D:\CZSC\anaconda3\envs\clpy37\lib\site-packages\spark_parser\ast.py", line 110, in preorder
    func(node)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\n_actions.py", line 144, in n_classdef
    self.n_classdef36(node)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\customize37.py", line 903, in n_classdef36
    self.build_class(subclass_code)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 953, in build_class
    self.gen_source(tree, code.co_name, code._customize)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 983, in gen_source
    self.text = self.traverse(tree, is_lambda=is_lambda)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 430, in traverse
    self.preorder(node)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 408, in preorder
    super(SourceWalker, self).preorder(node)
  File "D:\CZSC\anaconda3\envs\clpy37\lib\site-packages\spark_parser\ast.py", line 117, in preorder
    self.preorder(kid)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 408, in preorder
    super(SourceWalker, self).preorder(node)
  File "D:\CZSC\anaconda3\envs\clpy37\lib\site-packages\spark_parser\ast.py", line 110, in preorder
    func(node)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\customize37.py", line 998, in n_function_def
    self.default(node)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 802, in default
    self.template_engine(table[key.kind], node)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 692, in template_engine
    self.preorder(node[index])
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\pysource.py", line 408, in preorder
    super(SourceWalker, self).preorder(node)
  File "D:\CZSC\anaconda3\envs\clpy37\lib\site-packages\spark_parser\ast.py", line 110, in preorder
    func(node)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\n_actions.py", line 975, in n_mkfunc
    make_function36(self, node, is_lambda=False, code_node=code_node)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\semantics\make_function36.py", line 141, in make_function36
    scanner_code = Code(code, self.scanner, self.currentclass, debug_asm_opts)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\scanner.py", line 68, in __init__
    self._tokens, self._customize = scanner.ingest(co, classname, show_asm=show_asm)
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\scanners\scanner37.py", line 66, in ingest
    self, bytecode, classname, code_objects, show_asm
  File "d:\czsc\python逆向\python-decompile3-master\decompyle3\scanners\scanner37base.py", line 480, in ingest
    if "." in inst.argval:
TypeError: argument of type 'int' is not iterable

## Expected behavior
The output source can be compiled

## Environment
Python 3.7.8, Windows 11

## Workarounds
None

**Comment by OwnerCM** [comment]
I tried to modify line 480 of scanner37base.py to: 
if "." in str(inst.argval). 
The program can continue to execute, but in the end it still reports an error: Deparsing stopped due to parse error, and the output result file has many bytecode.

**Comment by OwnerCM** [comment]
> `ORT_NAME` has an invalid value.

I have a license file and it can run normally. 
Is there any solution to the operand of IMPORT_NAME has an invalid value?

**Comment by rocky** [comment]
Reread the section [Do you have valid bytecode?](https://github.com/rocky/python-decompile3/blob/master/HOW-TO-REPORT-A-BUG.md#do-you-have-valid-bytecode) under "Is it Really a Bug?"

With respect to the [Ethics](https://github.com/rocky/python-decompile3/blob/master/HOW-TO-REPORT-A-BUG.md#ethics) section, why do you need to decompile `cl.py`?

**Comment by OwnerCM** [comment]
> Reread the section [Do you have valid bytecode?](https://github.com/rocky/python-decompile3/blob/master/HOW-TO-REPORT-A-BUG.md#do-you-have-valid-bytecode) under "Is it Really a Bug?"
> 
> With respect to the [Ethics](https://github.com/rocky/python-decompile3/blob/master/HOW-TO-REPORT-A-BUG.md#ethics) section, why do you need to decompile `cl.py`?

thanks for the reply! Decompilation is because the author cannot provide the source code after purchase, and the calculation logic needs to be seen during the program analysis process.
