### ISSUE TITLE
Exception:  'Instruction' object has no attribute 'tos_str'

### ISSUE THREAD

**Issue by pfremy** [rocky/python-decompile3#158]
## Description

My situation is the following : I have lost the source for the last release of one of my software. I am trying to recover the source, but I still have all the previous releases to make a reasonable comparison with.

Here, I tried using decompyle3 but it failed with an exception. I attach the successful decompilation of uncompyle6 for reference.

## How to Reproduce

```console
> decompyle3 logh_gui.pyc
# decompyle3 version 3.9.1.dev0
# Python bytecode version base 3.7.0 (3394)
# Decompiled from: Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
# Embedded file name: logh_gui.py
Traceback (most recent call last):
  File "C:\work\logh_home\.env\Scripts\decompyle3-script.py", line 33, in <module>
    sys.exit(load_entry_point('decompyle3', 'console_scripts', 'decompyle3')())
  File "C:\work\logh_home\.env\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\work\logh_home\.env\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\work\logh_home\.env\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\work\logh_home\.env\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\work\logh_home\python-decompile3\decompyle3\bin\decompile.py", line 146, in main_bin
    result = main(
  File "c:\work\logh_home\python-decompile3\decompyle3\main.py", line 337, in main
    deparsed_objects = decompile_file(
  File "c:\work\logh_home\python-decompile3\decompyle3\main.py", line 238, in decompile_file
    decompile(
  File "c:\work\logh_home\python-decompile3\decompyle3\main.py", line 158, in decompile
    deparsed = deparse_fn(
  File "c:\work\logh_home\python-decompile3\decompyle3\semantics\pysource.py", line 1120, in code_deparse
    tokens, customize = scanner.ingest(
  File "c:\work\logh_home\python-decompile3\decompyle3\scanners\scanner37.py", line 65, in ingest
    tokens, customize = Scanner37Base.ingest(
  File "c:\work\logh_home\python-decompile3\decompyle3\scanners\scanner37base.py", line 672, in ingest
    tos_str=inst.tos_str,
AttributeError: 'Instruction' object has no attribute 'tos_str'
```

## Attached files
[logh_gui.zip](https://github.com/rocky/python-decompile3/files/13361446/logh_gui.zip)

I include the output of uncompyle6 so that you can more easily reproduce.

## Environment

Decompyle version from current sources : 

```
(.env) C:\work\logh_home\python-decompile3>git log -1
commit ed375df6b21ecbddd21cf6aaa37c7673da876751 (HEAD -> master, origin/master, origin/HEAD)
Author: rocky <rb@dustyfeet.com>
Date:   Mon Nov 13 08:09:43 2023 -0500

    Forgot to add these to the last commit

```

- trusting uncompyle6, it was compiled with Python 3.7
- Windows 10 22H2

## Priority

Up to you...

I was willing to test the recently fixed if condition handling on my decompiled program.

**Comment by pfremy** [comment]
[toto.zip](https://github.com/rocky/python-decompile3/files/13362243/toto.zip)

Much smaller example to reproduce the bug

**Comment by rocky** [comment]
All bytecode attached decompiles fine using the current versions of code. 

> I was willing to test the recently fixed if condition handling on my decompiled program.

Ok. I was willing to test running the decompyle3 on all of the bytecode attached. It looks to me like decompyle3 does a more correct and more idiomatic translation.

**Comment by pfremy** [comment]
This is what my environment looks like :

```
(.env) C:\work\logh_home\log_enhancer.exe_extracted>pip list
Package      Version    Location
------------ ---------- -----------------------------------
click        8.1.7
colorama     0.4.6
decompyle3   3.9.1.dev0 c:\work\logh_home\python-decompile3
pip          21.2.4
setuptools   58.1.0
six          1.16.0
spark-parser 1.8.9
uncompyle6   3.9.0
xdis         6.0.5
```

What I am missing to make it work ?

**Comment by pfremy** [comment]
I had a look at circle-ci and found the difference. You are using git version of xdis. With this, it worked.
