### ISSUE TITLE
KeyError: 67660

### ISSUE THREAD

**Issue by Xcating** [rocky/python-decompile3#163]
## Description

run  the
```shell
decompyle3 pvzrouge.pyc
``` 
pop up error KeyError: 67660

## How to Reproduce

```shell
decompyle3 pvzrouge.pyc
``` 
[PVZ-Rouge.zip](https://github.com/rocky/python-decompile3/files/14449873/PVZ-Rouge.zip)

[pvzrouge.zip](https://github.com/rocky/python-decompile3/files/14449818/pvzrouge.zip)

## Output Given

```batchfile
Traceback (most recent call last):
  File "e:\python308\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\python308\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Python308\Scripts\decompyle3.exe\__main__.py", line 9, in <module>
  File "e:\python308\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "e:\python308\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "e:\python308\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\python308\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "e:\python308\lib\site-packages\decompyle3\bin\decompile.py", line 109, in main_bin
    result = main(
  File "e:\python308\lib\site-packages\decompyle3\main.py", line 327, in main
    deparsed_objects = decompile_file(
  File "e:\python308\lib\site-packages\decompyle3\main.py", line 231, in decompile_file
    decompile(
  File "e:\python308\lib\site-packages\decompyle3\main.py", line 158, in decompile
    deparsed = deparse_fn(
  File "e:\python308\lib\site-packages\decompyle3\semantics\pysource.py", line 1104, in code_deparse
    tokens, customize = scanner.ingest(
  File "e:\python308\lib\site-packages\decompyle3\scanners\scanner38.py", line 67, in ingest
    tokens, customize = super(Scanner38, self).ingest(
  File "e:\python308\lib\site-packages\decompyle3\scanners\scanner37.py", line 65, in ingest
    tokens, customize = Scanner37Base.ingest(
  File "e:\python308\lib\site-packages\decompyle3\scanners\scanner37base.py", line 352, in ingest
    jump_inst = self.insts[self.offset2inst_index[inst.argval]]
KeyError: 67660
``` 

## Expected behavior

Successfully output pvzrooge.py
## Environment

decompyle3, version 3.9.0
Python 3.8.0
Windows 11
PIP LIST
``` 
Package      Version
------------ -------
click        8.1.7
colorama     0.4.6
decompyle3   3.9.0
pip          19.2.3
setuptools   41.2.0
six          1.16.0
spark-parser 1.8.9
uncompyle6   3.9.0
xdis         6.0.5
```

**Comment by rocky** [comment]
While this is a legitimate bug in the code and will be fixed by #165, It will take a while to decompile. The reason why is a known problem which will eventually get addressed. 

This is a somewhat large and pathological program probably created by some game generator.

While it is not clear that using decomplation to cheat at games may not be strictly illegal, it is questionable ethically. 

Please do not use this issue tracker to assist you to do things that may not be ethical.
