### ISSUE TITLE
It didn't work when there is a `return` in an `except` block with an `as`

### ISSUE THREAD

**Issue by Unnamed-py** [rocky/python-decompile3#42]
## Description

This module does not seem to be able to decompile when there is a `return` in an `except` block with an `as`.

## How to Reproduce

My code:
```python
import decompyle3


def bug():
    try:
        pass
    except ValueError as exc:
        return


decompyle3.deparse_code2str(bug.__code__)

```

Output:
```
Instruction context:
   
 L.   8        22  POP_BLOCK        
                  24  POP_EXCEPT       
->                26  CALL_FINALLY         32  'to 32'
                  28  LOAD_CONST               None
                  30  RETURN_VALUE     
                32_0  COME_FROM            26  '26'
                32_1  COME_FROM_FINALLY    20  '20'
                  32  LOAD_CONST               None
                  34  STORE_FAST               'exc'
                  36  DELETE_FAST              'exc'
                  38  END_FINALLY      
                  40  POP_EXCEPT       
                  42  JUMP_FORWARD         46  'to 46'
                44_0  COME_FROM            12  '12'
                  44  END_FINALLY      
                46_0  COME_FROM            42  '42'
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\decompyle3\semantics\pysource.py", line 2127, in build_ast
    ast = python_parser.parse(self.p, tokens, customize, is_lambda=is_lambda)
  File "C:\Program Files\Python38\lib\site-packages\decompyle3\parsers\main.py", line 364, in parse
    ast = p.parse(tokens)
  File "C:\Program Files\Python38\lib\site-packages\spark_parser\spark.py", line 501, in parse
    self.error(tokens, i-1)
  File "C:\Program Files\Python38\lib\site-packages\decompyle3\parsers\main.py", line 208, in error
    raise ParserError(err_token, err_token.offset, self.debug["reduce"])
decompyle3.parsers.main.ParserError: Parse error at or near `CALL_FINALLY' instruction at offset 26


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<my code>", line 11, in <module>
    decompyle3.deparse_code2str(bug.__code__)
  File "C:\Program Files\Python38\lib\site-packages\decompyle3\semantics\pysource.py", line 2254, in deparse_code2str
    return code_deparse(
  File "C:\Program Files\Python38\lib\site-packages\decompyle3\semantics\pysource.py", line 2199, in code_deparse
    deparsed.ast = deparsed.build_ast(tokens, customize, co, isTopLevel=isTopLevel)
  File "C:\Program Files\Python38\lib\site-packages\decompyle3\semantics\pysource.py", line 2130, in build_ast
    raise ParserError(e, tokens, self.p.debug["reduce"])
decompyle3.semantics.parser_error.ParserError: --- This code section failed: ---

 L.   5         0  SETUP_FINALLY         6  'to 6'

 L.   6         2  POP_BLOCK        
                4  JUMP_FORWARD         46  'to 46'
              6_0  COME_FROM_FINALLY     0  '0'

 L.   7         6  DUP_TOP          
                8  LOAD_GLOBAL              ValueError
               10  COMPARE_OP               exception-match
               12  POP_JUMP_IF_FALSE    44  'to 44'
               14  POP_TOP          
               16  STORE_FAST               'exc'
               18  POP_TOP          
               20  SETUP_FINALLY        32  'to 32'

 L.   8        22  POP_BLOCK        
               24  POP_EXCEPT       
               26  CALL_FINALLY         32  'to 32'
               28  LOAD_CONST               None
               30  RETURN_VALUE     
             32_0  COME_FROM            26  '26'
             32_1  COME_FROM_FINALLY    20  '20'
               32  LOAD_CONST               None
               34  STORE_FAST               'exc'
               36  DELETE_FAST              'exc'
               38  END_FINALLY      
               40  POP_EXCEPT       
               42  JUMP_FORWARD         46  'to 46'
             44_0  COME_FROM            12  '12'
               44  END_FINALLY      
             46_0  COME_FROM            42  '42'
             46_1  COME_FROM             4  '4'

Parse error at or near `CALL_FINALLY' instruction at offset 26

```

## Expected behavior

I want it to print my raw code in the function `bug`.

## Environment
OS: Windows10 64-bit
Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
decompyle3.version.VERSION: 3.3.2

**Comment by cnSchwarzer** [comment]
Why this closed?

**Comment by rocky** [comment]
It works for me. Version used is VERSION: 3.3.2. Latest version is 3.7.5 or so.
