### ISSUE TITLE
run with error

### ISSUE THREAD

**Issue by mangopaq** [rocky/python-decompile3#50]
```
Traceback (most recent call last):
  File "/usr/local/bin/decompyle3", line 33, in <module>
    sys.exit(load_entry_point('decompyle3==3.3.2', 'console_scripts', 'decompyle3')())
  File "/usr/local/bin/decompyle3", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/decompyle3-3.3.2-py3.8.egg/decompyle3/__init__.py", line 48, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/decompyle3-3.3.2-py3.8.egg/decompyle3/semantics/pysource.py", line 139, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/decompyle3-3.3.2-py3.8.egg/decompyle3/parsers/__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/decompyle3-3.3.2-py3.8.egg/decompyle3/parsers/treenode.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/decompyle3-3.3.2-py3.8.egg/decompyle3/scanners/tok.py", line 201, in <module>
  File "/usr/local/lib/python3.8/site-packages/decompyle3-3.3.2-py3.8.egg/decompyle3/scanners/tok.py", line 83, in __init__
  File "/usr/local/lib/python3.8/site-packages/xdis/std.py", line 220, in <module>
    _std_api = make_std_api()
  File "/usr/local/lib/python3.8/site-packages/xdis/std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "/usr/local/lib/python3.8/site-packages/xdis/std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "/usr/local/lib/python3.8/site-packages/xdis/op_imports.py", line 170, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.8.7'
[root@py38 ~]# python3 -V
```

**Comment by rocky** [comment]
Update to the latest version of xdis and you should be fine.

**Comment by arabelladonna** [comment]
I'm getting a similar issue in Python 3.8.8 on Windows 10, which happens with or without arguments.

```
D:\Code\Python\python-decompile3>decompyle3
Traceback (most recent call last):
  File "D:\Applications\Python\Python38\Scripts\decompyle3-script.py", line 33, in <module>
    sys.exit(load_entry_point('decompyle3', 'console_scripts', 'decompyle3')())
  File "D:\Applications\Python\Python38\Scripts\decompyle3-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "d:\applications\python\python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "d:\applications\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\code\python\python-decompile3\decompyle3\__init__.py", line 48, in <module>
    import decompyle3.semantics.pysource
  File "d:\code\python\python-decompile3\decompyle3\semantics\pysource.py", line 139, in <module>
    import decompyle3.parsers.main as python_parser
  File "d:\code\python\python-decompile3\decompyle3\parsers\__init__.py", line 13, in <module>
    from decompyle3.parsers.treenode import *
  File "d:\code\python\python-decompile3\decompyle3\parsers\treenode.py", line 2, in <module>
    from decompyle3.scanners.tok import NoneToken, Token
  File "d:\code\python\python-decompile3\decompyle3\scanners\tok.py", line 201, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
  File "d:\code\python\python-decompile3\decompyle3\scanners\tok.py", line 83, in __init__
    from xdis.std import _std_api
  File "d:\applications\python\python38\lib\site-packages\xdis\std.py", line 220, in <module>
    _std_api = make_std_api()
  File "d:\applications\python\python38\lib\site-packages\xdis\std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "d:\applications\python\python38\lib\site-packages\xdis\std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "d:\applications\python\python38\lib\site-packages\xdis\op_imports.py", line 170, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.8.8'
```

I'm apparently using the latest version of xdis.

```
D:\Code\Python\python-decompile3>pip install xdis
Requirement already satisfied: xdis in d:\applications\python\python38\lib\site-packages (5.0.7)
```
