### ISSUE TITLE
KeyError: '3.9.2'

### ISSUE THREAD

**Issue by Gowixx** [rocky/python-decompile3#55]
## Description
KeyError

## How to Reproduce
Download python 3.9.2 and download decompyle3

## Expected behavior
Give a response

## Environment
Windows

## Additional Environment or Context
When I type decomyple3 it responds with `KeyError: '3.9.2'`

**Comment by harsh18262** [comment]
Same Problem on linux(arch) using both python 3.8.8 and 3.9.2

**Comment by harsh18262** [comment]
Complete error:

Traceback (most recent call last):
  File "/home/captain/.local/bin/decompyle3", line 5, in <module>
    from decompyle3.bin.decompile import main_bin
  File "/home/captain/.local/lib/python3.9/site-packages/decompyle3/__init__.py", line 48, in <module>
    import decompyle3.semantics.pysource
  File "/home/captain/.local/lib/python3.9/site-packages/decompyle3/semantics/pysource.py", line 139, in <module>
    import decompyle3.parsers.main as python_parser
  File "/home/captain/.local/lib/python3.9/site-packages/decompyle3/parsers/__init__.py", line 13, in <module>
    from decompyle3.parsers.treenode import *
  File "/home/captain/.local/lib/python3.9/site-packages/decompyle3/parsers/treenode.py", line 2, in <module>
    from decompyle3.scanners.tok import NoneToken, Token
  File "/home/captain/.local/lib/python3.9/site-packages/decompyle3/scanners/tok.py", line 201, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
  File "/home/captain/.local/lib/python3.9/site-packages/decompyle3/scanners/tok.py", line 83, in __init__
    from xdis.std import _std_api
  File "/usr/lib/python3.9/site-packages/xdis/std.py", line 220, in <module>
    _std_api = make_std_api()
  File "/usr/lib/python3.9/site-packages/xdis/std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "/usr/lib/python3.9/site-packages/xdis/std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "/usr/lib/python3.9/site-packages/xdis/op_imports.py", line 170, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.9.2'

**Comment by Clemens-Dautermann** [comment]
I have the same Issue.
python version: 3.9.2
OS: Arch Linux

**Comment by rocky** [comment]
Update [xdis](https://pypi.org/project/xdis/) to version 5.0.8 and you'll be okay

**Comment by gioxc88** [comment]
I have the same issue with python 3.8.10 updated xdis same error

**Comment by rocky** [comment]
same answer.

**Comment by gioxc88** [comment]
> same answer.

Not sure what you mean by that. I did what you suggested in the answer (updating xdis) but I still get same error
