### ISSUE TITLE
I'm trying to translate a * .pyc file * .py file and got the following errors. what is the problem. Can anyone help?

### ISSUE THREAD

**Issue by kuratkull** [rocky/python-decompile3#57]
i got the same error with uncompyle6.
```
Traceback (most recent call last):
  File "C:\Users\Q\AppData\Local\Programs\Python\Python39\Scripts\decompyle3-script.py", line 33, in <module>
    sys.exit(load_entry_point('decompyle3', 'console_scripts', 'decompyle3')())
  File "C:\Users\Q\AppData\Local\Programs\Python\Python39\Scripts\decompyle3-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\Q\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\Q\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\Q\desktop\python-decompile3-master\decompyle3\__init__.py", line 48, in <module>
    import decompyle3.semantics.pysource
  File "c:\users\Q\desktop\python-decompile3-master\decompyle3\semantics\pysource.py", line 139, in <module>
    import decompyle3.parsers.main as python_parser
  File "c:\users\Q\desktop\python-decompile3-master\decompyle3\parsers\__init__.py", line 13, in <module>
    from decompyle3.parsers.treenode import *
  File "c:\users\Q\desktop\python-decompile3-master\decompyle3\parsers\treenode.py", line 2, in <module>
    from decompyle3.scanners.tok import NoneToken, Token
  File "c:\users\Q\desktop\python-decompile3-master\decompyle3\scanners\tok.py", line 201, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
  File "c:\users\Q\desktop\python-decompile3-master\decompyle3\scanners\tok.py", line 83, in __init__
    from xdis.std import _std_api
  File "c:\users\Q\appdata\local\programs\python\python39\lib\site-packages\xdis\std.py", line 220, in <module>
    _std_api = make_std_api()
  File "c:\users\Q\appdata\local\programs\python\python39\lib\site-packages\xdis\std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "c:\users\Q\appdata\local\programs\python\python39\lib\site-packages\xdis\std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "c:\users\Q\appdata\local\programs\python\python39\lib\site-packages\xdis\op_imports.py", line 173, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.9.5'
```

**Comment by rocky** [comment]
https://github.com/rocky/python-decompile3/issues/45
