### ISSUE TITLE
Unknown type 0

### ISSUE THREAD

**Issue by m0hamedessam** [rocky/python-decompile3#58]
Unknown type 0
Traceback (most recent call last):
  File "/usr/local/bin/decompyle3", line 11, in <module>
    load_entry_point('decompyle3==3.3.2', 'console_scripts', 'decompyle3')()
  File "/usr/local/lib/python3.8/dist-packages/decompyle3-3.3.2-py3.8.egg/decompyle3/bin/decompile.py", line 189, in main_bin
  File "/usr/local/lib/python3.8/dist-packages/decompyle3-3.3.2-py3.8.egg/decompyle3/main.py", line 296, in main
  File "/usr/local/lib/python3.8/dist-packages/decompyle3-3.3.2-py3.8.egg/decompyle3/main.py", line 207, in decompile_file
  File "/usr/local/lib/python3.8/dist-packages/decompyle3-3.3.2-py3.8.egg/decompyle3/main.py", line 80, in decompile
AssertionError

I got this error any idea ?

**Comment by rocky** [comment]
Yes, my first idea is that you don't read and/or follow instructions. Come back fter looking at https://github.com/rocky/python-decompile3/issues/new?assignees=&labels=&template=bug-report.md
