### ISSUE TITLE
Can't install decompyle3 on windows 10

### ISSUE THREAD

**Issue by euzada** [rocky/python-decompile3#59]
hi, I am having this error each time I tried to install decompyle3 when I tried after to run it alone.

This is how I install it.

pip install git+https://github.com/rocky/python-decompile3

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\decompyle3.exe\__main__.py", line 4, in <module>
  File "c:\python39\lib\site-packages\decompyle3\__init__.py", line 48, in <module>
    import decompyle3.semantics.pysource
  File "c:\python39\lib\site-packages\decompyle3\semantics\pysource.py", line 139, in <module>
    import decompyle3.parsers.main as python_parser
  File "c:\python39\lib\site-packages\decompyle3\parsers\__init__.py", line 13, in <module>
    from decompyle3.parsers.treenode import *
  File "c:\python39\lib\site-packages\decompyle3\parsers\treenode.py", line 2, in <module>
    from decompyle3.scanners.tok import NoneToken, Token
  File "c:\python39\lib\site-packages\decompyle3\scanners\tok.py", line 201, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
  File "c:\python39\lib\site-packages\decompyle3\scanners\tok.py", line 83, in __init__
    from xdis.std import _std_api
  File "c:\python39\lib\site-packages\xdis\std.py", line 220, in <module>
    _std_api = make_std_api()
  File "c:\python39\lib\site-packages\xdis\std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "c:\python39\lib\site-packages\xdis\std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "c:\python39\lib\site-packages\xdis\op_imports.py", line 173, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.9.6'

**Comment by pydsigner** [comment]
@euzada do you have xdis 5.0.11?

**Comment by otis-zeny** [comment]
hi this what im getting ,any help will be appriciated

luka\python-decompile3-master> decompyle3
decompyle3 : The term 'decompyle3' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ decompyle3
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (decompyle3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundExceptio

**Comment by BoranCanOzel** [comment]
Same problem

**Comment by rishavraj543256** [comment]
use this command in cmd to install decompyle3 on windows10
pip install https://github.com/rocky/python-decompile3

**Comment by ImInTheICU** [comment]
that dont even work

**Comment by rocky** [comment]
This is better suited as something on a forum geared for basic user help.
