### ISSUE TITLE
Decompiling pyc ImportError

### ISSUE THREAD

**Issue by lukehowlett97** [rocky/python-decompile3#63]
Trying to run decompyle3 -o . ~\Root.pyc
ImportError: Ill-formed bytecode file C:\Users\Root.exe_extracted\Root.pyc
<class 'AssertionError'>; co_code should be one of the types (<class 'str'>, <class 'bytes'>, <class 'list'>, <class 'tuple'>); is type <class 'NoneType'>

No idea how to fix this problem sorry, could anyone help I would be very grateful.

Full error:

```
Unknown type 0
Unknown type 100 d
Unknown type 0
Unknown type 100 d
Unknown type 1 ☺
Unknown type 100 d
Unknown type 2 ☻
Unknown type 100 d
Traceback (most recent call last):
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\load.py", line 301, in load_module_from_file_object
    co = xdis.unmarshal.load_code(fp, magic_int, code_objects)
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\unmarshal.py", line 530, in load_code
    return um_gen.load()
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\unmarshal.py", line 167, in load
    return self.r_object()
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\unmarshal.py", line 205, in r_object
    return unmarshal_func(save_ref, bytes_for_s)
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\unmarshal.py", line 488, in t_code
    code = to_portable(
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\codetype\__init__.py", line 203, in to_portable
    return codeType2Portable(code, version)
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\codetype\__init__.py", line 66, in codeType2Portable
    return Code38(
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\codetype\code38.py", line 102, in __init__
    self.check()
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\codetype\code13.py", line 87, in check
    assert type(val) in fieldtype, "%s should be one of the types %s; is type %s" % (field, fieldtype, type(val))
AssertionError: co_code should be one of the types (<class 'str'>, <class 'bytes'>, <class 'list'>, <class 'tuple'>); is type <class 'NoneType'>
Traceback (most recent call last):
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\load.py", line 301, in load_module_from_file_object
    co = xdis.unmarshal.load_code(fp, magic_int, code_objects)
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\unmarshal.py", line 530, in load_code
    return um_gen.load()
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\unmarshal.py", line 167, in load
    return self.r_object()
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\unmarshal.py", line 205, in r_object
    return unmarshal_func(save_ref, bytes_for_s)
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\unmarshal.py", line 488, in t_code
    code = to_portable(
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\codetype\__init__.py", line 203, in to_portable
    return codeType2Portable(code, version)
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\codetype\__init__.py", line 66, in codeType2Portable
    return Code38(
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\codetype\code38.py", line 102, in __init__
    self.check()
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\codetype\code13.py", line 87, in check
    assert type(val) in fieldtype, "%s should be one of the types %s; is type %s" % (field, fieldtype, type(val))
AssertionError: co_code should be one of the types (<class 'str'>, <class 'bytes'>, <class 'list'>, <class 'tuple'>); is type <class 'NoneType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chcuk\anaconda3\Scripts\decompyle3-script.py", line 33, in <module>
    sys.exit(load_entry_point('decompyle3', 'console_scripts', 'decompyle3')())
  File "c:\users\chcuk\onedrive\desktop\python-decompile3-master\decompyle3\bin\decompile.py", line 189, in main_bin
    result = main(
  File "c:\users\chcuk\onedrive\desktop\python-decompile3-master\decompyle3\main.py", line 296, in main
    deparsed = decompile_file(
  File "c:\users\chcuk\onedrive\desktop\python-decompile3-master\decompyle3\main.py", line 182, in decompile_file
    (version, timestamp, magic_int, co, is_pypy, source_size, sip_hash) = load_module(
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\load.py", line 167, in load_module
    return load_module_from_file_object(
  File "c:\users\chcuk\anaconda3\lib\site-packages\xdis\load.py", line 310, in load_module_from_file_object
    raise ImportError(
ImportError: Ill-formed bytecode file C:\Users\chcuk\OneDrive\Desktop\pyinstxtractor-master\Root.exe_extracted\Root.pyc
<class 'AssertionError'>; co_code should be one of the types (<class 'str'>, <class 'bytes'>, <class 'list'>, <class 'tuple'>); is type <class 'NoneType'>
```

**Comment by Wav3lonNights** [comment]
how you fixed it?
