### ISSUE TITLE
Error while using decompyle3

### ISSUE THREAD

**Issue by mte0** [rocky/python-decompile3#77]
Any time I try to run a decompyle3 command, including help, I just get an error message.

I have tried installing decompyle3 via pypi and download this repo and setting up.

Python 3.9
Windows 10 64bit x64

`D:\path>decompyle3
Traceback (most recent call last):
  File "C:\Python39\Scripts\decompyle3-script.py", line 33, in <module>
    sys.exit(load_entry_point('decompyle3', 'console_scripts', 'decompyle3')())
  File "C:\Python39\Scripts\decompyle3-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Python39\lib\site-packages\decompyle3\__init__.py", line 34, in <module>
    from xdis import PYTHON_VERSION_TRIPLE
ImportError: cannot import name 'PYTHON_VERSION_TRIPLE' from 'xdis' (C:\Python39\lib\site-packages\xdis\__init__.py)`

This also happens if I try to use `decompyle3 file.pyc` or the help command

**Comment by rocky** [comment]
It doesn't look like anyone wants to help you.
